// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Api from "./Api.res.mjs";
import * as React from "react";
import * as Header from "./Header.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function CategorieList(props) {
  var match = React.useState(function () {
        return [];
      });
  var setCategorieList = match[1];
  React.useEffect((function () {
          var makeRequest = async function () {
            var data = await Api.fetchCategorie();
            return setCategorieList(function (param) {
                        return data;
                      });
          };
          makeRequest();
        }), []);
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx(Header.make, {}),
                JsxRuntime.jsx("h1", {
                      children: "Liste des categories"
                    }),
                JsxRuntime.jsx("ul", {
                      children: match[0].map(function (categorie) {
                            return JsxRuntime.jsx("li", {
                                        children: categorie.name + " "
                                      }, categorie.id.toString());
                          })
                    })
              ]
            });
}

var make = CategorieList;

export {
  make ,
}
/* react Not a pure module */
