// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Api from "./Api.res.mjs";
import * as React from "react";
import * as JsxRuntime from "react/jsx-runtime";

function ClothingList(props) {
  var match = React.useState(function () {
        return [];
      });
  var setClothingList = match[1];
  React.useEffect((function () {
          var makeRequest = async function () {
            var data = await Api.fetchClothing();
            return setClothingList(function (param) {
                        return data;
                      });
          };
          makeRequest();
        }), []);
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "Liste des vêtements"
                    }),
                JsxRuntime.jsx("ul", {
                      children: match[0].map(function (clothing) {
                            return JsxRuntime.jsxs("li", {
                                        children: [
                                          clothing.name + " - " + clothing.price.toString() + " €",
                                          JsxRuntime.jsx("img", {
                                                alt: clothing.name,
                                                src: clothing.imageUrl
                                              })
                                        ]
                                      }, clothing.id.toString());
                          })
                    })
              ]
            });
}

var make = ClothingList;

export {
  make ,
}
/* react Not a pure module */
