// Generated by ReScript, PLEASE EDIT WITH CARE

import * as HelloWorld from "../HelloWorld.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function Home(props) {
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx(HelloWorld.make, {
                    name: "Mika"
                  }),
              className: "p-6"
            });
}

var make = Home;

export {
  make ,
}
/* HelloWorld Not a pure module */
